[workspace]
members = ["payjoin", "payjoin-cli", "payjoin-directory", "payjoin-test-utils"]
resolver = "2"
exclude = ["payjoin-ffi"]

[patch.crates-io]
payjoin = { path = "payjoin" }
payjoin-directory = { path = "payjoin-directory" }
payjoin-test-utils = { path = "payjoin-test-utils" }